{
    "items":[
        {   "id":				"complements",
            "type":			"Education",
            "label":			"Education",
            "startdate":		"2002-09",
            "enddate":		"2010-10",
            "description":	"Subjects studied included General Technology, Prospective and Prevision, Systemics, Knowledge Management",
            "institution":	"MIT OpenCourses, ENSAM, MCX",
            "department":		"System Sciences",
            "technologies":	"Systemics, Operational Research, Complex Thinking, KM",
            "city":			"Paris",
            "state":			"France",
            "latlng":			"48.858391,2.349701",
            "imageURL":		"img/pierre.jpg"
         },
         {
            "id":				"complexe",
            "type":			"research",
            "label":			"research",
            "startdate":		"2005-04",
            "enddate":		"2010-10",
            "description":	"Participation to the UNESCO project on Technology Management",
            "institution":	"UNESCO, MCX APC",
            "department":		"Complex Systems",
            "technologies":	"Systemics, Complexity Organisation, Complex Thinking, KM",
            "city":			"Paris",
            "state":			"France",
            "latlng":			"48.858391,2.349701",
            "imageURL":		"img/un.jpg"
         },
         {
            "id":				"masterinsciences",
            "type":			"Education",
            "label":			"Master in Sciences and Engineering",
            "startdate":		"1997-07",
            "enddate":		"2002-07",
            "description":	"Subjects studied included Physical Sciences, Mechanics, Materials, Electronics, Energetics, Industrial Management and Computer Sciences",
            "institution":	"ECAM",
            "department":		"Engineering",
            "technologies":	"Mechanics, Materials, Electronics, Energetics, Industrial Management, Computer Sciences",
            "city":			"Lyon",
            "state":			"France",
            "latlng":			"45.744526980468436,4.8779296875",
            "imageURL":		"img/ecam.jpg"
         },
         {
            "id":				"suezlef",
            "type":			"job",
            "label":			"IT Governance Project Support",
            "startdate":		"2002-02",
            "enddate":		"2002-07",
            "description":	"Support the Information System Architecture and Urbanisation Project : BPM Business Process Management, Applicative cartography",
            "institution":	"Suez Lyonnaise des Eaux",
            "department":		"Information Systems",
            "technologies":	"ARIS, BPM, MEGA, Cartograhy, Information Systems Urbanism",
            "city":			"Paris",
            "state":			"France",
            "latlng":			"48.858391,2.349701",
            "imageURL":		"img/suez.jpg"
         },
         {
            "id":				"CFFP",
            "type":			"job",
            "label":			"Product Engineering",
            "startdate":		"2003-06",
            "enddate":		"2004-09",
            "description":	"Support product engineering and production, control quality, organize logistics",
            "institution":	"CFFP",
            "department":		"Construction",
            "technologies":	"CAD, THALES, Structural calculations, Eurocode, ISO 14 000, ISO 9001, Six Sigma",
            "city":			"Lyon",
            "state":			"France",
            "latlng":			"45.744,4.8779296875",
            "imageURL":		"img/chalet.jpg"
         },
         {
            "id":				"IBM",
            "type":			"job",
            "label":			"IT Support Analyst",
            "startdate":		"2005-09",
            "enddate":		"2006-09",
            "description":	"Support the IBM Global Services for the EMEA area, deliver service desk support on various environment, support critical systems infrastructures. Work with international support teams",
            "institution":	"IBM",
            "department":		"Global IT services",
            "technologies":	"IBM Lotus Domino, Microsoft, Echange, MVS, AS400, Unix",
            "city":			"Dublin",
            "state":			"Ireland",
            "latlng":			"53.357109,-6.256714",
            "imageURL":		"img/ibm.jpg"
         },
         {
            "id":				"HP",
            "type":			"job",
            "label":			"IT Support Analyst",
            "startdate":		"2006-10",
            "enddate":		"2007-09",
            "description":	"provide support operation, service desk 1st, 2nd level, work with international support teams",
            "institution":	"HP (Hewlettt Packard)",
            "department":		"Global IT services",
            "technologies":	"Windows Xp, Windows server 03, Exchange, SAP, VPN, Symantec",
            "city":			"Dublin",
            "state":			"Ireland",
            "latlng":			"53.357109,-6.256714",
            "imageURL":		"img/hp.jpg"
         },
         {
            "id":				"Dalkia",
            "type":			"job",
            "label":			"IT Project Manager",
            "startdate":		"2007-10",
            "enddate":		"2008-01",
            "description":	"Support implementation of new Customer Service IT System, training, evaluation, strategic alignement with Dalkia UK",
            "institution":	"Dalkia",
            "department":		"Technical Services",
            "technologies":	"FSI Concept, SQL Server, VPN, PMI project, MS Project",
            "city":			"Dublin",
            "state":			"Ireland",
            "latlng":			"53.357109,-6.256714",
            "imageURL":		"img/dalkia.jpg"
         },
         {
            "id":				"Nobel",
            "type":			"job",
            "label":			"VIP IT support",
            "startdate":		"2008-03",
            "enddate":		"2010-02",
            "description":	"IT support headquater and VIP, local IT support, manage Site and Systems (network, machines, SMS, telephony, organize conferences and webcasts",
            "institution":	"NobelBiocare",
            "department":		"Informatique",
            "technologies":	"Windows Xp, Office, WIndows Server, VPN, WAN, Telephony, VOIP, Blackberry, Nokia",
            "city":			"Zurich",
            "state":			"Switzerland",
            "latlng":			"47.361153,8.51",
            "imageURL":		"img/nobelbio.jpg"
		
        },
         {
            "id":				"HP Hewlett Packard",
            "type":			"job",
            "label":			"Storage specialist",
            "startdate":		"2010-05",
            "enddate":		"2011-07",
            "description":	"IT support and Storage specialist",
            "institution":	"HP Hewlett Packard",
            "department":		"Informatique",
            "technologies":	"Windows Server 2003, Windows Server 2008, IBM SAN, HP Hardware, EMC Legato",
            "city":			"Bern",
            "state":			"Switzerland",
            "latlng":			"47.361153,8.51",
            "imageURL":		"img/hp.jpg"
		
        },
         {
            "id":				"Xerox",
            "type":			"job",
            "label":			"IT specialist",
            "startdate":		"2011-07",
            "enddate":		"2016-10",
            "description":	"IT support",
            "institution":	"Xerox",
            "department":		"Informatique",
            "technologies":	"Windows 7, Dell, Server 2003, Sharepoint",
            "city":			"Zurich",
            "state":			"Switzerland",
            "latlng":			"47.361153,8.51",
            "imageURL":		"img/xerox.jpg"
		
        },
         {
            "id":				"EPO - WIPO",
            "type":			"research",
            "label":			"IT Patent Engineer",
            "startdate":		"2016-07",
            "enddate":		"2020-10",
            "description":	"R&D Novel IT Technologies",
            "institution":	"EPO - WIPO",
            "department":		"Informatique",
            "technologies":	"Quantum Computing, Complex Systems Modeling, Knowledge Management",
            "city":			"Den Haag",
            "state":			"Holland",
            "latlng":			"47.361153,8.51",
            "imageURL":		"img/wipo.jpg"
		
        },
         {
            "id":				"KRATZER-AUTOMATION",
            "type":			"job",
            "label":			"System Integrator",
            "startdate":		"2021-01",
            "enddate":		"2021-07",
            "description":	"System Integrator Cloud - Edge",
            "institution":	"KRATZER-AUTOMATION",
            "department":		"Informatique",
            "technologies":	"java, mysql, apache, wildfly, aws, Linux, Microsoft",
            "city":			"Paris",
            "state":			"France",
            "latlng":			"48.858400,2.3496",
            "imageURL":		"img/ka.jpg"
		
        }
       ],
	"types" :      {
		"job" : {"label" :       "Work"},
		"research" : {"label" :       "Research"},
		"title" : {"label" :       "Education"}
	}
}
